### PR TITLE
Fix #53

### LINKED ISSUE #53: Control Panel not returned when disassembled
When reconfiguring a control panel, it can be placed in the creator and disassembled. If it your intention for the panel not to be returned?

It is a bit expensive in terms of iron and copper for the item to be replaced every time a panel needs adjusting.

Thanks for the mod, its fun and your videos explaining how to use the mod.

IndustrialWires-1.7-33
ImmersiveEngineering-0.12-86
forge-1.12.2-14.23.5.2768-universal

### PR DESCRIPTION
**Pull request by anar4732**
Fix #53

### CODE REVIEW

**Comment by malte0811** [comment]
The problem is that this was, at least originally (when it was a machine casing rather than a custom item), very much intended. The idea is that once you make holes all over the panel (which is how you mount the components), it isn't usable for other "layouts". I just never got around to implementing a proper system that tracks where there'd be holes on the returned panel. Thinking about it, that could work quite well to give panels a "patched"/re-used look as well. I'll look into changing it to return the panel in some way, but I can't promise anything right now (Uni is taking a lot of time currently).

**Comment by anar4732** [comment]
What? What? What? What Hole? Why did not merged this?

**Comment by malte0811** [comment]
> Why did not merged this?

I didn't merge this because, as I said above, I don't like this solution to the "problem" (which is a design choice, though I accept that the current state isn't ideal) and am planning to implement a solution that I like better in the next couple of weeks.

 > What Hole?

IRL you mount components on control panels by drilling/cutting a hole in the case of the panel and screwing the component into that hole. IW uses the same concept, that's why the panel creator looks something like a small CNC mill. After disassembly the case/unfinished panel has holes where the components were placed, which means it can't really be used for new control panels unless the component placement is very similar, you like to have holes in your panel or you place some sort of cover over the holes. That's what I'm planning to do, return an unfinished panel with the old mounting holes still present that can be covered up with some sort of cheap "cover" component. Creating panels with uncovered holes will either be impossible or cause them to malfunction/short out when they are left in the rain.

**Comment by anar4732** [comment]
if you do, it would be nice for the panel maker to work with electricity.

**Pull request closed without merging**
